# MONK 1

# DATA  PREPROCESSING

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
%matplotlib inline

In [2]:
import warnings

def fxn():
    warnings.warn("deprecated", DeprecationWarning)

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    fxn()
warnings.filterwarnings("ignore")

In [3]:
df_train=pd.read_csv("/Users/matteoppa/Desktop/ML/ML_project_2020/train1.csv",sep=' ',header=None)
df_test=pd.read_csv("/Users/matteoppa/Desktop/ML/ML_project_2020/test1.csv",sep=' ',header=None)

In [4]:
df_train.columns = ["trash","Class","a1","a2","a3","a4","a5","a6","id"]

In [5]:
df_test.columns = ["trash","Class","a1","a2","a3","a4","a5","a6","id"]

In [6]:
df_train.drop('trash',
  axis='columns', inplace=True)
df_train.drop("id", axis='columns', inplace=True)

In [7]:
df_test.drop('trash',
  axis='columns', inplace=True)
df_test.drop("id", axis='columns', inplace=True)

In [8]:
scaler = MinMaxScaler()
# transform data
scaled_train = scaler.fit_transform(df_train)
scaled_test = scaler.fit_transform(df_test)

In [9]:
y = df_train["Class"]
X = df_train.drop("Class", axis =1)


In [10]:
y_t = df_test["Class"]
X_t = df_test.drop("Class", axis=1)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.20)

# CV - SVC

In [12]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.svm import SVC

In [13]:
#1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5

In [14]:
# Qui faccio la cross validation per stimare i parametri
tuned_parameters = [{'kernel': ['rbf'], 'gamma': [1, 0.5, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5],
                     'C': [1e-5, 1e-4, 1e-3, 1e-2, 1e-1]},
                    {'kernel': ['linear'], 'C': [1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 0.5]}]

scores = ['precision', 'recall']

for score in scores:
    print("# Tuning hyper-parameters for %s" % score)
    print()

    clf = GridSearchCV(
        SVC(), tuned_parameters, scoring='%s_macro' % score
    )
    clf.fit(X_train, y_train)

    print("Best parameters set found on development set:")
    print()
    print(clf.best_params_)
    print()
    print("Grid scores on development set:")
    print()
    means = clf.cv_results_['mean_test_score']
    stds = clf.cv_results_['std_test_score']
    for mean, std, params in zip(means, stds, clf.cv_results_['params']):
        print("%0.3f (+/-%0.03f) for %r"
              % (mean, std * 2, params))
    print()

    print("Detailed classification report:")
    print()
    print("The model is trained on the full development set.")
    print("The scores are computed on the full evaluation set.")
    print()
    y_true, y_pred = y_val, clf.predict(X_val)
    print(classification_report(y_true, y_pred))
    print()

# Tuning hyper-parameters for precision

Best parameters set found on development set:

{'C': 0.1, 'gamma': 0.1, 'kernel': 'rbf'}

Grid scores on development set:

0.263 (+/-0.022) for {'C': 1e-05, 'gamma': 1, 'kernel': 'rbf'}
0.263 (+/-0.022) for {'C': 1e-05, 'gamma': 0.5, 'kernel': 'rbf'}
0.263 (+/-0.022) for {'C': 1e-05, 'gamma': 0.1, 'kernel': 'rbf'}
0.263 (+/-0.022) for {'C': 1e-05, 'gamma': 0.01, 'kernel': 'rbf'}
0.263 (+/-0.022) for {'C': 1e-05, 'gamma': 0.001, 'kernel': 'rbf'}
0.263 (+/-0.022) for {'C': 1e-05, 'gamma': 0.0001, 'kernel': 'rbf'}
0.263 (+/-0.022) for {'C': 1e-05, 'gamma': 1e-05, 'kernel': 'rbf'}
0.263 (+/-0.022) for {'C': 0.0001, 'gamma': 1, 'kernel': 'rbf'}
0.263 (+/-0.022) for {'C': 0.0001, 'gamma': 0.5, 'kernel': 'rbf'}
0.263 (+/-0.022) for {'C': 0.0001, 'gamma': 0.1, 'kernel': 'rbf'}
0.263 (+/-0.022) for {'C': 0.0001, 'gamma': 0.01, 'kernel': 'rbf'}
0.263 (+/-0.022) for {'C': 0.0001, 'gamma': 0.001, 'kernel': 'rbf'}
0.263 (+/-0.022) for {'C': 0.0001, 'gamma': 

In [15]:
print(clf.best_estimator_)

SVC(C=0.1, kernel='linear')


In [16]:
grid_predictions = clf.predict(X_t)

In [17]:
print(confusion_matrix(y_t,grid_predictions))

[[160  56]
 [ 80 136]]


In [18]:
print(classification_report(y_t,grid_predictions))

              precision    recall  f1-score   support

           0       0.67      0.74      0.70       216
           1       0.71      0.63      0.67       216

    accuracy                           0.69       432
   macro avg       0.69      0.69      0.68       432
weighted avg       0.69      0.69      0.68       432



In [20]:
#Per definizione si ha overfit se training accuracy > test accuracy poichè il modello non generalizza.

# MONK 2

# IMPORT DATA

In [21]:
df_train_2=pd.read_csv("/Users/matteoppa/Desktop/ML/ML_project_2020/train2.csv",sep=' ',header=None)
df_test_2=pd.read_csv("/Users/matteoppa/Desktop/ML/ML_project_2020/test2.csv",sep=' ',header=None)

In [22]:
df_train_2.columns = ["trash","Class","a1","a2","a3","a4","a5","a6","id"]

In [23]:
df_test_2.columns = ["trash","Class","a1","a2","a3","a4","a5","a6","id"]

In [24]:
df_train_2.drop('trash',
  axis='columns', inplace=True)
df_train_2.drop("id", axis='columns', inplace=True)

In [25]:
df_test_2.drop('trash',
  axis='columns', inplace=True)
df_test_2.drop("id", axis='columns', inplace=True)

In [26]:
scaler = MinMaxScaler()
# transform data
scaled_train_2 = scaler.fit_transform(df_train_2)
scaled_test_2= scaler.fit_transform(df_test_2)

In [27]:
y_2 = df_train_2["Class"]
X_2 = df_train_2.drop("Class", axis =1)

In [28]:
yt_2 = df_test_2["Class"]
Xt_2 = df_test_2.drop("Class", axis =1)

# MODEL SELECTION

In [29]:
X_train_2, X_val_2, y_train_2, y_val_2 = train_test_split(X_2, y_2, test_size = 0.20)

In [30]:
# Qui faccio la cross validation per stimare i parametri
tuned_parameters_2 = [{'kernel': ['rbf'], 'gamma': [1e-1, 1e-2, 1e-3, 1e-4, 1e-5],
                     'C': [1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 0.5]},
                    {'kernel': ['linear'], 'C': [1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 0.5]},{'kernel': ['poly'], 'C': [1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 0.5], 'degree': [1, 2, 3, 4, 5, 6, 7]}]

scores_2 = ['precision', 'recall']

for score in scores_2:
    print("# Tuning hyper-parameters for %s" % score)
    print()

    clf_2 = GridSearchCV(
        SVC(), tuned_parameters_2, scoring='%s_macro' % score
    )
    clf_2.fit(X_train_2, y_train_2)

    print("Best parameters set found on development set:")
    print()
    print(clf_2.best_params_)
    print()
    print("Grid scores on development set:")
    print()
    means = clf_2.cv_results_['mean_test_score']
    stds = clf_2.cv_results_['std_test_score']
    for mean, std, params in zip(means, stds, clf_2.cv_results_['params']):
        print("%0.3f (+/-%0.03f) for %r"
              % (mean, std * 2, params))
    print()

    print("Detailed classification report:")
    print()
    print("The model is trained on the full development set.")
    print("The scores are computed on the full evaluation set.")
    print()
    y_true_2, y_pred_2 = y_val_2, clf_2.predict(X_val_2)
    print(classification_report(y_true_2, y_pred_2))
    print()

# Tuning hyper-parameters for precision

Best parameters set found on development set:

{'C': 0.1, 'degree': 7, 'kernel': 'poly'}

Grid scores on development set:

0.311 (+/-0.015) for {'C': 1e-05, 'gamma': 0.1, 'kernel': 'rbf'}
0.311 (+/-0.015) for {'C': 1e-05, 'gamma': 0.01, 'kernel': 'rbf'}
0.311 (+/-0.015) for {'C': 1e-05, 'gamma': 0.001, 'kernel': 'rbf'}
0.311 (+/-0.015) for {'C': 1e-05, 'gamma': 0.0001, 'kernel': 'rbf'}
0.311 (+/-0.015) for {'C': 1e-05, 'gamma': 1e-05, 'kernel': 'rbf'}
0.311 (+/-0.015) for {'C': 0.0001, 'gamma': 0.1, 'kernel': 'rbf'}
0.311 (+/-0.015) for {'C': 0.0001, 'gamma': 0.01, 'kernel': 'rbf'}
0.311 (+/-0.015) for {'C': 0.0001, 'gamma': 0.001, 'kernel': 'rbf'}
0.311 (+/-0.015) for {'C': 0.0001, 'gamma': 0.0001, 'kernel': 'rbf'}
0.311 (+/-0.015) for {'C': 0.0001, 'gamma': 1e-05, 'kernel': 'rbf'}
0.311 (+/-0.015) for {'C': 0.001, 'gamma': 0.1, 'kernel': 'rbf'}
0.311 (+/-0.015) for {'C': 0.001, 'gamma': 0.01, 'kernel': 'rbf'}
0.311 (+/-0.015) for {'C': 0.001, 

In [31]:
print(clf_2.best_estimator_)

SVC(C=0.1, degree=7, kernel='poly')


In [32]:
grid_predictions_2 = clf_2.predict(Xt_2)

In [33]:
print(confusion_matrix(yt_2,grid_predictions_2))

[[217  73]
 [ 41 101]]


In [34]:
print(classification_report(yt_2,grid_predictions_2))

              precision    recall  f1-score   support

           0       0.84      0.75      0.79       290
           1       0.58      0.71      0.64       142

    accuracy                           0.74       432
   macro avg       0.71      0.73      0.72       432
weighted avg       0.76      0.74      0.74       432



# MONK 3

# DATA IMPORT

In [35]:
df_train_3=pd.read_csv("/Users/matteoppa/Desktop/ML/ML_project_2020/train3.csv",sep=' ',header=None)
df_test_3=pd.read_csv("/Users/matteoppa/Desktop/ML/ML_project_2020/test3.csv",sep=' ',header=None)

In [36]:
df_train_3.columns = ["trash","Class","a1","a2","a3","a4","a5","a6","id"]

In [37]:
df_test_3.columns = ["trash","Class","a1","a2","a3","a4","a5","a6","id"]

In [38]:
df_train_3.drop('trash',
  axis='columns', inplace=True)
df_train_3.drop("id", axis='columns', inplace=True)

In [39]:
df_test_3.drop('trash',
  axis='columns', inplace=True)
df_test_3.drop("id", axis='columns', inplace=True)

In [40]:
scaler = MinMaxScaler()
# transform data
scaled_train_3 = scaler.fit_transform(df_train_2)
scaled_test_3= scaler.fit_transform(df_test_2)

In [41]:
y_3 = df_train_3["Class"]
X_3 = df_train_3.drop("Class", axis =1)

In [42]:
yt_3 = df_test_3["Class"]
Xt_3 = df_test_3.drop("Class", axis =1)

# MODEL SELECTION

In [43]:
X_train_3, X_val_3, y_train_3, y_val_3 = train_test_split(X_3, y_3, test_size = 0.20)

In [44]:
tuned_parameters_3 = [{'kernel': ['rbf'], 'gamma': [1e-1, 1e-2, 1e-3, 1e-4, 1e-5],
                     'C': [1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 0.5]},
                    {'kernel': ['linear'], 'C': [1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 0.5]}]

scores_3 = ['precision', 'recall']

for score in scores_2:
    print("# Tuning hyper-parameters for %s" % score)
    print()

    clf_3 = GridSearchCV(
        SVC(), tuned_parameters_3, scoring='%s_macro' % score
    )
    clf_3.fit(X_train_3, y_train_3)

    print("Best parameters set found on development set:")
    print()
    print(clf_3.best_params_)
    print()
    print("Grid scores on development set:")
    print()
    means = clf_3.cv_results_['mean_test_score']
    stds = clf_3.cv_results_['std_test_score']
    for mean, std, params in zip(means, stds, clf_3.cv_results_['params']):
        print("%0.3f (+/-%0.03f) for %r"
              % (mean, std * 2, params))
    print()

    print("Detailed classification report:")
    print()
    print("The model is trained on the full development set.")
    print("The scores are computed on the full evaluation set.")
    print()
    y_true_3, y_pred_3 = y_val_3, clf_2.predict(X_val_3)
    print(classification_report(y_true_3, y_pred_3))
    print()

# Tuning hyper-parameters for precision

Best parameters set found on development set:

{'C': 0.5, 'gamma': 0.1, 'kernel': 'rbf'}

Grid scores on development set:

0.258 (+/-0.013) for {'C': 1e-05, 'gamma': 0.1, 'kernel': 'rbf'}
0.258 (+/-0.013) for {'C': 1e-05, 'gamma': 0.01, 'kernel': 'rbf'}
0.258 (+/-0.013) for {'C': 1e-05, 'gamma': 0.001, 'kernel': 'rbf'}
0.258 (+/-0.013) for {'C': 1e-05, 'gamma': 0.0001, 'kernel': 'rbf'}
0.258 (+/-0.013) for {'C': 1e-05, 'gamma': 1e-05, 'kernel': 'rbf'}
0.258 (+/-0.013) for {'C': 0.0001, 'gamma': 0.1, 'kernel': 'rbf'}
0.258 (+/-0.013) for {'C': 0.0001, 'gamma': 0.01, 'kernel': 'rbf'}
0.258 (+/-0.013) for {'C': 0.0001, 'gamma': 0.001, 'kernel': 'rbf'}
0.258 (+/-0.013) for {'C': 0.0001, 'gamma': 0.0001, 'kernel': 'rbf'}
0.258 (+/-0.013) for {'C': 0.0001, 'gamma': 1e-05, 'kernel': 'rbf'}
0.258 (+/-0.013) for {'C': 0.001, 'gamma': 0.1, 'kernel': 'rbf'}
0.258 (+/-0.013) for {'C': 0.001, 'gamma': 0.01, 'kernel': 'rbf'}
0.258 (+/-0.013) for {'C': 0.001, 

In [45]:
print(clf_3.best_estimator_)

SVC(C=0.5, gamma=0.1)


In [46]:
grid_predictions_3 = clf_3.predict(Xt_3)

In [47]:
print(confusion_matrix(yt_3,grid_predictions_3))

[[198   6]
 [ 34 194]]


In [48]:
print(classification_report(yt_3,grid_predictions_3))

              precision    recall  f1-score   support

           0       0.85      0.97      0.91       204
           1       0.97      0.85      0.91       228

    accuracy                           0.91       432
   macro avg       0.91      0.91      0.91       432
weighted avg       0.91      0.91      0.91       432

